### PR TITLE
 Include vector_tools.templates.h for deal.II 8.3.0 support

### PR DESCRIPTION
**Pull request by spco**
Aspect doesn't build in Xcode 7.0.1 (Clang-700.0.72) using deal 8.3.0 MacOSX package unless this include is added.

### CODE REVIEW

**Comment by tjhei** [comment]
What is the error message you are getting if it is not included?

**Comment by spco** [comment]
Undefined symbols for architecture x86_64:
  "void dealii::VectorTools::compute_no_normal_flux_constraints<2, dealii::DoFHandler, 2>(dealii::DoFHandler<2, 2> const&, unsigned int, std::__1::set<unsigned char, std::__1::less<unsigned char>, std::__1::allocator<unsigned char> > const&, dealii::ConstraintMatrix&, dealii::Mapping<2, 2> const&)", referenced from:
      aspect::Simulator<2>::setup_dofs() in core.o
      aspect::Simulator<2>::FreeSurfaceHandler::make_constraints() in freesurface.o
  "void dealii::VectorTools::compute_no_normal_flux_constraints<3, dealii::DoFHandler, 3>(dealii::DoFHandler<3, 3> const&, unsigned int, std::__1::set<unsigned char, std::__1::less<unsigned char>, std::__1::allocator<unsigned char> > const&, dealii::ConstraintMatrix&, dealii::Mapping<3, 3> const&)", referenced from:
      aspect::Simulator<3>::setup_dofs() in core.o
      aspect::Simulator<3>::FreeSurfaceHandler::make_constraints() in freesurface.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please correct me if this is a setup error on my part! I'm on MacOSX 10.11.

**Comment by tjhei** [comment]
This is interesting. @bangerth we instantiate the following (see https://github.com/dealii/dealii/blob/dealii-8.3/source/numerics/vector_tools_constraints.inst.in):
```
  template
  void
  compute_no_normal_flux_constraints (const DoFHandler<deal_II_dimension> &dof_handler,
                                      const unsigned int     first_vector_component,
                                      const std::set<types::boundary_id> &boundary_ids,
                                      ConstraintMatrix      &constraints,
                                      const Mapping<deal_II_dimension>    &mapping);
```
but the linker is still unhappy. I don't see the problem.

**Comment by spco** [comment]
I can confirm I've had to include this same header in the other project I've worked on since using 8.3.0.

**Comment by bangerth** [comment]
Hm, this makes no sense. @spco -- did you install deal.II 8.3 from Luca's dmg packages, or yourself? In the latter case, can you run this command on your machine (assuming that `nm` is something that's available on OS X):
```
  cd /the/directory/in/which/you/built/dealii
  cd source/numerics/CMakeFiles/obj_numerics.debug.dir
  nm -C vector_tools_constraints.cc.o | grep no_normal_flux
```
This should print out the functions that were instantiated and compiled. For me this yields
```
0000000000000000 W void dealii::VectorTools::compute_no_normal_flux_constraints<2, dealii::DoFHandler, 2>(dealii::DoFHandler<2, 2> const&, unsigned int, std::set<unsigned char, std::less<unsigned char>, std::allocator<unsigned char> > const&, dealii::ConstraintMatrix&, dealii::Mapping<2, 2> const&)
0000000000000000 W void dealii::VectorTools::compute_no_normal_flux_constraints<2, dealii::hp::DoFHandler, 2>(dealii::hp::DoFHandler<2, 2> const&, unsigned int, std::set<unsigned char, std::less<unsigned char>, std::allocator<unsigned char> > const&, dealii::ConstraintMatrix&, dealii::Mapping<2, 2> const&)
0000000000000000 W void dealii::VectorTools::compute_no_normal_flux_constraints<3, dealii::DoFHandler, 3>(dealii::DoFHandler<3, 3> const&, unsigned int, std::set<unsigned char, std::less<unsigned char>, std::allocator<unsigned char> > const&, dealii::ConstraintMatrix&, dealii::Mapping<3, 3> const&)
0000000000000000 W void dealii::VectorTools::compute_no_normal_flux_constraints<3, dealii::hp::DoFHandler, 3>(dealii::hp::DoFHandler<3, 3> const&, unsigned int, std::set<unsigned char, std::less<unsigned char>, std::allocator<unsigned char> > const&, dealii::ConstraintMatrix&, dealii::Mapping<3, 3> const&)
```

**Comment by spco** [comment]
Hi @bangerth , no I used Luca's dmg package. I will reinstall this over the next couple of hours to double-check that it's reproducible.

**Comment by spco** [comment]
I've reinstalled the package and reproduced this. I haven't tried from source, as it was too much pain last time!

**Comment by bangerth** [comment]
I've opened an issue with deal.II at https://github.com/dealii/dealii/issues/1752 . Let's see if we can get some feedback from Luca there.

I guess that for the moment at least you have a workaround. This gives us time to investigate this properly.

**Comment by spco** [comment]
Thanks. Shall I close this request, as it's not an aspect bug?

**Comment by bangerth** [comment]
No, let's keep it open if we really have to work around a problem in ASPECT.

**Comment by bangerth** [comment]
I don't quite know how to proceed here. @spco -- if you use the most recent MAC package and remove the workaround you have in ASPECT, do you still get the linker error?

**Comment by spco** [comment]
Hi @bangerth - I'll try this in the next few days and let you know!

**Comment by spco** [comment]
I've retried with the Mac package from the website - it doesn't seem to have had any effect.

**Comment by bangerth** [comment]
Hm, I really don't know what's going on here, but the patch is pretty harmless. @tjhei -- any objections to just applying this?

**Comment by tjhei** [comment]
@spco can you please add a comment before the include that explains why this is there?

/run-tests

**Comment by spco** [comment]
Doh! I've messed up my local branch (pulled in a load from my other branch) and pushed it by accident - I'll fix this in the morning! Sorry! :)

**Comment by bangerth** [comment]
A `git rebase -i master` should pretty easily allow you to throw away all but the commits you care about.

**Comment by spco** [comment]
Right, I think I've finally fixed it!
