### PR TITLE
[Urgent] Fix 'main' breakage.

### PR DESCRIPTION
**Pull request by bangerth**
This fix breakage such as this that currently trips up #5207 and #5206:
```
/__w/aspect/aspect/source/particle/property/strain_rate.cc:49:15: error: cannot bind non-const lvalue reference of type 'dealii::ArrayView<double, dealii::MemorySpace::Host>&' to an rvalue of type 'dealii::ArrayView<double, dealii::MemorySpace::Host>'
   49 |         auto &data = particle->get_properties();
      |               ^~~~
/__w/aspect/aspect/source/particle/property/strain_rate.cc: In instantiation of 'void aspect::Particle::Property::StrainRate<dim>::update_particle_property(unsigned int, const dealii::Vector<double>&, const std::vector<dealii::Tensor<1, dim> >&, typename dealii::Particles::ParticleHandler<dim>::particle_iterator&) const [with int dim = 3; typename dealii::Particles::ParticleHandler<dim>::particle_iterator = dealii::Particles::ParticleIterator<3, 3>]':
/__w/aspect/aspect/source/particle/property/strain_rate.cc:96:7:   required from here
/__w/aspect/aspect/source/particle/property/strain_rate.cc:49:15: error: cannot bind non-const lvalue reference of type 'dealii::ArrayView<double, dealii::MemorySpace::Host>&' to an rvalue of type 'dealii::ArrayView<double, dealii::MemorySpace::Host>'
In file included from CMakeFiles/aspect.dir/Unity/unity_24_cxx.cxx:17:
/__w/aspect/aspect/source/particle/property/viscoplastic_strain_invariants.cc: In instantiation of 'void aspect::Particle::Property::ViscoPlasticStrainInvariant<dim>::update_particle_property(unsigned int, const dealii::Vector<double>&, const std::vector<dealii::Tensor<1, dim> >&, typename dealii::Particles::ParticleHandler<dim>::particle_iterator&) const [with int dim = 2; typename dealii::Particles::ParticleHandler<dim>::particle_iterator = dealii::Particles::ParticleIterator<2, 2>]':
/__w/aspect/aspect/source/particle/property/viscoplastic_strain_invariants.cc:232:7:   required from here
/__w/aspect/aspect/source/particle/property/viscoplastic_strain_invariants.cc:133:15: error: cannot bind non-const lvalue reference of type 'dealii::ArrayView<double, dealii::MemorySpace::Host>&' to an rvalue of type 'dealii::ArrayView<double, dealii::MemorySpace::Host>'
  133 |         auto &data = particle->get_properties();
      |               ^~~~
```
This is caused by https://github.com/dealii/dealii/pull/15671.

### CODE REVIEW

File: source/particle/property/integrated_strain.cc [hunk 1]
```diff
@@ -43,7 +43,7 @@ namespace aspect
                                                       const std::vector<Tensor<1,dim>> &gradients,
                                                       typename ParticleHandler<dim>::particle_iterator &particle) const
       {
-        auto &data = particle->get_properties();
+        const auto data = particle->get_properties();
```
Comment (bangerth) [inline source/particle/property/integrated_strain.cc:46]: `get_properties()` used to return a `const ArrayView<...>` object. It isn't a reference, so capturing it with `auto &` was always a poor design choice. It worked because the compiler deduced `auto = const ArrayView`, and binding a temporary to a const reference is allowed. But https://github.com/dealii/dealii/pull/15671 changed the return type to drop the `const`, which means that the compiler deduces `auto = ArrayView`, and now we have a non-const reference for which the returned temporary is no longer able to bind -- and the compiler errors out.

**Review by tjhei — APPROVED** [review]
