### ISSUE TITLE
particle cell_weight error with deal.II master

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#5250]
The deal.ii master tester currently fails with
```
/opt/deal.II-master/include/deal.II/bundled/boost/function/function_template.hpp:137:22: error: no match for call to '(aspect::Particle::World<dim>::initialize() [with int dim = 2]::<lambda(const cell_iterator&, dealii::Triangulation<2, 2>::CellStatus)>) (const dealii::TriaIterator<dealii::CellAccessor<2, 2> >&, dealii::CellStatus)'
```
which is caused by https://github.com/dealii/dealii/pull/15576

I am working on it.

**Comment by bangerth** [comment]
Is this fixed by #5251? Can it be closed?
