### ISSUE TITLE
build failure in tensor with deal.II master

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#6128]
```
/__w/aspect/aspect/build/CMakeFiles/aspect.exe.debug.dir/Unity/unity_42_cxx.cxx
In file included from /opt/deal.II-master/include/deal.II/base/symmetric_tensor.h:25,
                 from /opt/deal.II-master/include/deal.II/base/array_view.h:22,
                 from /opt/deal.II-master/include/deal.II/base/mpi.h:20,
                 from /__w/aspect/aspect/include/aspect/global.h:27,
                 from /__w/aspect/aspect/build/CMakeFiles/aspect.exe.debug.dir/cmake_pch.hxx:5,
                 from <command-line>:
/opt/deal.II-master/include/deal.II/base/tensor.h: In instantiation of 'constexpr dealii::Tensor<rank_, dim, Number>::operator dealii::Tensor<1, dim, dealii::Tensor<(rank_ - 1), dim, OtherNumber> >() const [with OtherNumber = double; int rank_ = 2; int dim = 3; Number = double]':
/__w/aspect/aspect/source/solution_evaluator.cc:120:95:   required from 'aspect::small_vector<dealii::Tensor<1, dim> > aspect::internal::DynamicFEPointEvaluationImpl<dim, n_components>::get_gradient(unsigned int) const [with int dim = 3; int n_components = 3; aspect::small_vector<dealii::Tensor<1, dim> > = boost::container::small_vector<dealii::Tensor<1, 3>, 100, void, void>]'
/__w/aspect/aspect/source/solution_evaluator.cc:118:9:   required from here
/opt/deal.II-master/include/deal.II/base/tensor.h:1429:20: error: 'std::conditional_t<false, Kokkos::Array<double, 3, void>, Kokkos::Array<dealii::Tensor<1, 3>, 3, void> >' {aka 'const struct Kokkos::Array<dealii::Tensor<1, 3>, 3, void>'} has no member named 'begin'
 1429 |   std::copy(values.begin(), values.end(), x.values.begin());
```
see https://github.com/geodynamics/aspect/actions/runs/11666737070/job/32482395151#step:4:191

likely caused by https://github.com/dealii/dealii/pull/17744

**Comment by tjhei** [comment]
already fixed by https://github.com/dealii/dealii/pull/17838
