### PR TITLE
Fix nullspace removal

### PR DESCRIPTION
**Pull request by ian-r-rose**
Addresses #304.

Taking a crack at patching up the nullspace removal, and I thought I'd ask everyone their opinion here.  First of all, I've added some important and previously-missing routines, (angular momentum in 3D, linear momentum).

Second, I've managed to confuse myself a bit.  The new angular momentum removal function seems to fix the solid body rotation problem in #304.  So that is all well and good.  However, I am puzzled about the net rotation removal.  The strategy we have used is

* construct a solid body rotation (or translation) vector, under the theory that we know it is in the nullspace for specific cases
* project that solid body rotation (or translation) out of the solution vector using solution = solution - (rotation*solution) rotation

So my questions are:
(1) Is this obviously flawed?
(2) If so, is it worth trying to fix, or should we just stick to the more physical angular/linear momentum removal routines?
(3) This PR currently does not allow separate removal of x,y,or z translations.  It just removes all momentum.  Are there specific use cases where we need the granularity to specify which direction to remove?

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Thinking on this after some sleep, it seems clearer.  The current net_translation or net_rotation removal confuses the inner product over the finite element space (which has JxW weights) with the simple vector dot product.

My questions (2) and (3) remain, I think.

**Comment by tjhei** [comment]
What happens if you are in a 3d box that is say periodic in x direction, no flux in y direction, and free in z direction? I guess you want to remove only some translations then.

One other thing that comes to mind about this: I got a feature request a while ago (don't remember who asked), to remove angular momentum based on integration over a certain depth range. For example removing the rotation from the lower mantle only.

**Comment by ian-r-rose** [comment]
Your example is correct, though in that case the only momentum in the solution should be in the x direction, no?  So removing the total momentum should be equivalent to removing the x momentum.  If we want to retain that functionality, we certainly can, though.  I just thought I'd ask before going to the trouble of implementing.

Do you agree with my diagnosis of the problem?  What about net translations vs net momentum?

Removing angular momentum over a depth range should be possible, though I'd like to resolve this bug first.

**Comment by ian-r-rose** [comment]
Okay, I think this should:

*fix things
*not break any prm files
*include some previously un-implemented functionality

So, I suppose I can take style/correctness comments and questions now.

**Comment by bangerth** [comment]
> Your example is correct, though in that case the only momentum in the solution
> should be in the x direction, no? So removing the total momentum should be
> equivalent to removing the x momentum.

No. Think of a situation where you impose a pressure at the bottom, tangential 
flow at the top, and periodicity at the left or right. This allows for 
horizontal translation. I think if you have an incompressible medium, then 
whatever spatially variable pressure you prescribe at the bottom, you'll end 
up with a net zero vertical velocity component when integrated over the 
domain. But, if you have a compressible medium, I imagine that you can 
construct cases where either the net vertical velocity or momentum are nonzero.


> Removing angular momentum over a depth range should be possible, though I'd
> like to resolve this bug first.

Yes, I think one step at a time :-)

File: include/aspect/simulator.h [hunk 1]
```diff
@@ -1093,13 +1084,36 @@ namespace aspect
...
+       * (which corresponds to removing a net rotation instead of net angular
+       * momentum). 
+       *
+       * This function is implemented in
+       * <code>source/simulator/nullspace.cc</code>.
        */
-      void remove_net_angular_momentum( LinearAlgebra::BlockVector &relevant_dst, LinearAlgebra::BlockVector &tmp_distributed_stokes);
+      void remove_net_angular_momentum( LinearAlgebra::BlockVector &relevant_dst, 
+                                        LinearAlgebra::BlockVector &tmp_distributed_stokes,
+                                        bool use_constant_density);
```
Comment (bangerth) [inline include/aspect/simulator.h]: Can you reorder this so that input arguments come before output arguments (and mark input args as `const`)?

File: include/aspect/simulator.h [hunk 2]
```diff
@@ -1093,13 +1084,36 @@ namespace aspect
...
+       * (which corresponds to removing a net translation instead of net linear
+       * momentum). 
+       *
+       * This function is implemented in
+       * <code>source/simulator/nullspace.cc</code>.
        */
-      void remove_net_linear_momentum( LinearAlgebra::BlockVector &relevant_dst, LinearAlgebra::BlockVector &tmp_distributed_stokes);
+      void remove_net_linear_momentum( LinearAlgebra::BlockVector &relevant_dst, 
+                                       LinearAlgebra::BlockVector &tmp_distributed_stokes,
+                                       bool use_constant_density);
```
Comment (bangerth) [inline include/aspect/simulator.h]: same here

File: source/simulator/nullspace.cc [hunk 3]
```diff
@@ -81,135 +90,184 @@ namespace aspect
     class Translation : public TensorFunction<1,dim>
     {
       private:
-        const unsigned int direction;
+        Tensor<1,dim> translation;
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: I think you should be able to keep it const.

File: source/simulator/nullspace.cc [hunk 4]
```diff
@@ -81,135 +90,184 @@ namespace aspect
...
+        //and creates a translation along that axis 
         Translation(const unsigned int d)
           :
-          direction(d)
+          translation( Point<dim>::unit_vector(d) )
+        {}
+
+        //Constructor for TensorFunction that takes a vector
+        //and creates a translation along that vector 
+        Translation(Tensor<1,dim> t)
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: make the argument a const reference.

**Comment by bangerth** [comment]
It's too late for me to have the brain power to really review the ideas behind your patch, so I'm just commenting on style issues etc -- I hope you don't take offense at the nitpicking. I'll get to the content later if Timo doesn't beat me to it.

File: source/simulator/nullspace.cc [hunk 5]
```diff
@@ -81,135 +90,184 @@ namespace aspect
...
 
+    Tensor<1,dim> local_momentum;
+    double local_mass;
 
+    //loop over all local cells
+    for (cell = dof_handler.begin_active(); cell != dof_handler.end(); ++cell)
+      if (cell->is_locally_owned())
+        {
+          fe.reinit (cell);
+          q_points = fe.get_quadrature_points();
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: You're copying the whole array here. You can avoid this by declaring `q_points` as a reference type right here:
```
  const std::vector<Point<dim> > &q_points = fe.get_quadrature_points();
```

File: source/simulator/nullspace.cc [hunk 6]
```diff
@@ -81,135 +90,184 @@ namespace aspect
...
+          Tensor<1,dim> velocity;
+          // actually compute the momentum and mass
+          for (unsigned int k=0; k< quadrature.size(); ++k)
+            {
+              // get the velocity and density at this quadrature point
+              for (unsigned int i=0; i<dim; ++i) velocity[i] = fe_vals[k][i];
+              double rho = (use_constant_density ? 1.0 : out.densities[k]);
+
+              local_momentum += fe.JxW(k) * velocity * rho;
+              local_mass += fe.JxW(k) * rho;
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: This is a stylistic issue: we tend to think of `JxW(q)` as the `dx` in integrals, and pretty much always have it at the end of the formula. There's no good reason to do it that way other than it being a habit and that having conventions such as these make it easier to read code (not because it's more correct this way, but simply because there is less of an element of surprise -- like the one that caught my eye here).

File: source/simulator/nullspace.cc [hunk 7]
```diff
@@ -81,135 +90,184 @@ namespace aspect
...
+          for (unsigned int i=0; i< q_points.size(); i++)
+            {
+              in.pressure[i] = fe_vals[i][introspection.component_indices.pressure];
+              in.temperature[i] = fe_vals[i][introspection.component_indices.temperature];
+              for (unsigned int c=0; c<parameters.n_compositional_fields; ++c)
+                in.composition[i][c] = fe_vals[i][introspection.component_indices.compositional_fields[c]];
+              in.position[i] = q_points[i];
+
+            }
+          material_model->evaluate(in, out);
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: That's a potentially expensive call, but you won't need it if `use_constant_density==true`.

File: source/simulator/nullspace.cc [hunk 8]
```diff
@@ -81,135 +90,184 @@ namespace aspect
...
+                     UpdateFlags(update_quadrature_points | update_JxW_values | update_values));
 
-      }
-  }
+    typename DoFHandler<dim>::active_cell_iterator cell;
+    std::vector<Point<dim> > q_points(quadrature.size());
+    std::vector<Vector<double> > fe_vals(quadrature.size(), Vector<double>(finite_element.n_components()));
 
+    Tensor<1,dim> local_momentum;
+    double local_mass;
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: need to initialize with zero.

File: source/simulator/nullspace.cc [hunk 9]
```diff
@@ -81,135 +90,184 @@ namespace aspect
...
-
-  template <>
-  void
-  Simulator<3>::remove_net_angular_momentum( LinearAlgebra::BlockVector &relevant_dst,
-                                             LinearAlgebra::BlockVector &tmp_distributed_stokes )
-  {
-    AssertThrow(false, ExcNotImplemented());
+    //copy into the locally relevant vector
+    relevant_dst.block(0) = tmp_distributed_stokes.block(0);
   }
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: Last comment for today: This function looks quite reasonable to me. Thanks for cleaning it up -- I think it's much better than it was before! Will continue with the angular momentum today.

File: source/simulator/nullspace.cc [hunk 10]
```diff
@@ -81,162 +90,213 @@ namespace aspect
...
+                }
+              material_model->evaluate(in, out);
+            }
 
+          Tensor<1,dim> velocity;
+          // actually compute the momentum and mass
+          for (unsigned int k=0; k< quadrature.size(); ++k)
+            {
+              // get the velocity and density at this quadrature point
+              for (unsigned int i=0; i<dim; ++i) velocity[i] = fe_vals[k][i];
```
Comment (tjhei) [inline source/simulator/nullspace.cc]: this assumes velocity starts at component 0. Can you add an assert for this at the beginning of this function?

File: source/simulator/nullspace.cc [hunk 11]
```diff
@@ -81,162 +90,213 @@ namespace aspect
...
+        if( !(parameters.nullspace_removal & NullspaceRemoval::linear_momentum_z) && dim == 3 )
+          velocity_correction[2] = 0.0;  //don't correct z translation
       }
-  }
-
 
+    // Now construct a translation vector with the desired rate and subtract it from our vector
+    internal::Translation<dim> translation( velocity_correction );
+    interpolate_onto_velocity_system(translation, correction);
+    tmp_distributed_stokes.block(introspection.block_indices.velocities).sadd(1.0, -1.0,correction);
```
Comment (tjhei) [inline source/simulator/nullspace.cc]: use ```.add(-1.0, correction)``` instead

File: source/simulator/nullspace.cc [hunk 12]
```diff
@@ -81,162 +90,213 @@ namespace aspect
...
+    // \int \rho (v + v_const) = 0
 
-    if (parameters.nullspace_removal & NullspaceRemoval::net_translation_z)
-      {
-        //Only do z direction if dim == 3
-        AssertThrow( dim == 3, ExcMessage("Can't remove z translational mode in 2 dimensions"));
-        funcs.push_back(std_cxx1x::shared_ptr<TensorFunction<1,dim> >(new internal::Translation<dim>(2)));
-      }
+    //vector for storing the correction to the velocity field
+    LinearAlgebra::Vector correction(tmp_distributed_stokes.block(introspection.block_indices.velocities));
```
Comment (tjhei) [inline source/simulator/nullspace.cc]: move to the bottom where it is first used

File: source/simulator/nullspace.cc [hunk 13]
```diff
@@ -81,162 +90,213 @@ namespace aspect
...
+    tmp_distributed_stokes.block(introspection.block_indices.velocities).sadd(1.0, -1.0,correction);
 
-  template <>
-  void
-  Simulator<3>::remove_net_angular_momentum( LinearAlgebra::BlockVector &relevant_dst,
-                                             LinearAlgebra::BlockVector &tmp_distributed_stokes )
-  {
-    AssertThrow(false, ExcNotImplemented());
+    //copy into the locally relevant vector
+    relevant_dst.block(0) = tmp_distributed_stokes.block(0);
```
Comment (tjhei) [inline source/simulator/nullspace.cc]: ```introspection.block_indices.velocities```

File: source/simulator/nullspace.cc [hunk 14]
```diff
@@ -81,162 +90,213 @@ namespace aspect
...
-            net_rotations_translations[i] /= net_rotations_translations[i].l2_norm();
-          }
+    QGauss<dim> quadrature(parameters.stokes_velocity_degree+1);
+    FEValues<dim> fe(mapping, finite_element, quadrature,
+                     UpdateFlags(update_quadrature_points | update_JxW_values | update_values));
 
-      }
-  }
+    typename DoFHandler<dim>::active_cell_iterator cell;
+    std::vector<Vector<double> > fe_vals(quadrature.size(), Vector<double>(finite_element.n_components()));
```
Comment (tjhei) [inline source/simulator/nullspace.cc]: would it be cleaner to use ```FeValuesExtractors``` here and in the cell loop?

File: source/simulator/nullspace.cc [hunk 15]
```diff
@@ -244,32 +304,78 @@ namespace aspect
...
+        tmp_distributed_stokes.block(introspection.block_indices.velocities).sadd(1.0, -1.0*rotation_rate,correction);
+
+      }
+    else
+      {
+        //sum up the local contributions to moment of inertia
+        SymmetricTensor<2,dim> moment_of_inertia;
+        for( unsigned int i=0; i < dim; ++i )
+          for(unsigned int j=0; j <= i; ++j )
+            moment_of_inertia[i][j] = Utilities::MPI::sum( local_moment_of_inertia[i][j], mpi_communicator);
```
Comment (tjhei) [inline source/simulator/nullspace.cc]: this is a lot of individual AllReduce calls. I am not sure how clean the code would look like if you stuff ```moment_of_inertia``` into a flat std::vector<double> instead, so you can just do one ```sum```.

File: source/simulator/parameters.cc [hunk 16]
```diff
@@ -426,7 +426,27 @@ namespace aspect
                          "and or rotations. Depending on what you specify here, these non-determined "
                          "modes will be removed from the velocity field at the end of the Stokes solve step.\n"
                          "Note that while more than operation can be selected it only makes sense to "
-                         "pick one rotational and one translational operation.");
+                         "pick one rotational and one translational operation."
+                         "\n\n"
+                         "There are two varieties of nullspace removal implemented: removing net linear/angular "
+                         "momentum, and removing net translations/rotations. For removing linear momentum we search "
+                         "for a constant velocity vector $\\bf c$ such that $\\int_\\Omega \\rho ({\\bf u - c}) = 0$. "
+                         "This man be solved by realizing that $\\int_\\Omega \\rho {\\bf u} = {\\bf p}$, the "
```
Comment (tjhei) [inline source/simulator/parameters.cc]: "man" ? :-)

**Comment by tjhei** [comment]
> Removing angular momentum over a depth range should be possible, though I'd
> like to resolve this bug first.

Sure, I just pointed it out so you can take this into consideration (you also asked how generic the solution should be in the future).

**Comment by tjhei** [comment]
Oh, one more thought: would it make more sense to write a section in the manual and refer to it from the parameters help instead of the text/formulas you have there now? Then the .prm won't blow up that much and the typesetting is easier. It would also allow you to describe when this procedure is necessary and easily link to a future cookbook example.

**Comment by tjhei** [comment]
I haven't tested it yet, but I will before we get ready to merge. We also need some new tests, I fear. /run-tests

File: source/simulator/nullspace.cc (hunk 15 above)
Comment (ian-r-rose) [inline source/simulator/nullspace.cc]: I agree.  I actually have a couple of utility functions lying around somewhere that do exactly that for types Tensor<1,dim> and SymmetricTensor<2,dim>.  Would those be useful to include?  I know that I have needed reductions over geometric/tensorial types several times...

**Comment by ian-r-rose** [comment]
Sure, I am happy to break out the text I have written into a short manual section.  It would certainly help in letting it be less cramped, and we could include an image.  I will get to these comments later today.

File: source/simulator/nullspace.cc (hunk 14 above)
Comment (ian-r-rose) [inline source/simulator/nullspace.cc]: Would I then need two value-extraction calls?  I am already getting the whole set of fe values in order to evaluate the material model.

Comment (tjhei) [inline source/simulator/nullspace.cc]: Sure, but there is no harm in doing that. Your code would then look like compute_depth_average() for example.

File: source/simulator/nullspace.cc (hunk 15 above)
Comment (bangerth) [inline source/simulator/nullspace.cc]: Yes, I think that would be useful. Just add them to deal.II's `Utilities::MPI` namespace if you don't mind.

Comment (ian-r-rose) [inline source/simulator/nullspace.cc]: dealii::Utilities::MPI or aspect::Utilities?

File: include/aspect/utilities.h [hunk 17]
```diff
@@ -392,4 +392,27 @@ namespace aspect
...
+      template<int dim>
+      Tensor<1,dim> 
+      reduce_tensor(const Tensor<1,dim> &local, const MPI_Comm &mpi_communicator);
+
+      /**
+       * Perform an MPI sum over the quantities in the given SymmetricTensor<2,dim>
+       */
+      template<int dim>
+      SymmetricTensor<2,dim> 
+      reduce_symmetric_tensor(const SymmetricTensor<2,dim> &local, const MPI_Comm &mpi_communicator);
```
Comment (bangerth) [inline include/aspect/utilities.h]: I thought of these as going into deal.II's `dealii::Utilities::MPI` where the other `sum` functions already are. I think `sum` would actually be a descriptive name for the function.

Comment (ian-r-rose) [inline include/aspect/utilities.h]: Yes, fair enough, I wasn't quite sure what you meant.  If these look
reasonable to you I can open a separate PR against deal.II.  Are they as
general as you would want?

If we did that, I would still have to implement a fallback here if the
deal.II version was not the dev version.

And yes, you are right, sum is a more descriptive name.

On Tue, Apr 21, 2015 at 6:51 PM, Wolfgang Bangerth <notifications@github.com

File: source/utilities.cc [hunk 18]
```diff
@@ -745,3 +745,65 @@ namespace aspect
...
+  {
+    namespace MPI
+    {
+      template<int dim>
+      Tensor<1,dim> 
+      reduce_tensor(const Tensor<1,dim> &local, const MPI_Comm &mpi_communicator)
+      {
+        std::vector<double> entries(dim);
+        std::vector<double> global_entries(dim);
+        Tensor<1,dim> global;
```
Comment (bangerth) [inline source/utilities.cc]: Use fixed-sized arrays `double entries[dim]` here since you know the size and don't need dynamic memory allocation. Move the declaration of `global` down to right above the first use. Restricting the live range of variables makes it so much easier to optimize for compilers.

File: source/utilities.cc [hunk 19]
```diff
@@ -745,3 +745,65 @@ namespace aspect
...
+
+        for(unsigned int i=0; i<dim; ++i)
+          entries[i] = local[i];
+
+        MPI_Allreduce (&entries[0], &global_entries[0], dim, MPI_DOUBLE,
```
Comment (bangerth) [inline source/utilities.cc]: I think there's actually a `Utilities::MPI::sum` function for arrays to which you can just defer here.

File: source/utilities.cc [hunk 20]
```diff
@@ -745,3 +745,65 @@ namespace aspect
...
+          global[i] = global_entries[i];
+
+        return global;
+      }
+
+      template<int dim>
+      SymmetricTensor<2,dim> 
+      reduce_symmetric_tensor(const SymmetricTensor<2,dim> &local, const MPI_Comm &mpi_communicator)
+      {
+        unsigned int n_entries = dim*(dim+1)/2;
```
Comment (bangerth) [inline source/utilities.cc]: You're looking for `SymmetricTensor::n_independent_elements`. I believe there are also `unroll` functions that allow you to go from tensor to array and back.

Same below with the arrays and `global` as in the other function.

Comment (bangerth) [inline source/utilities.cc]: Otherwise looks reasonable -- thanks for moving this to deal.II

I don't think you need fallbacks here -- we've always made the assumption that the ASPECT dev versions build on deal.II dev versions, and made sure we have a deal.II release before every ASPECT release.

File: source/utilities.cc (hunk 18 above)
Comment (ian-r-rose) [inline source/utilities.cc]: Interesting, I did not know that, but it makes sense. I suppose that is part of why top-of-the-block variable declarations were widely ignored in C89?

Comment (bangerth) [inline source/utilities.cc]: The original C language required all declarations to come before any code. This is historical because it was done that way in all previous languages as well, and because it makes it easy for compilers to determine memory layout before memory accesses. But it's a terrible practice from the perspective of code readability ("what type did this variable used in line 189 of the function have again, and where was it previously used?") and it makes it unnecessarily hard for compilers to optimize ("did the function that is called over here between declaration and use modify the variable or not?"). There is a substantial body of research that suggests that moving declarations as far down as possible is good practice all around. Going beyond this, you will find many places in deal.II and ASPECT where we do things like
```
  void f() {
     int i = 42;
     g(i);
     {       // open block
        int k=21;
        h(k);
     }  // close block; make sure 'k' goes out of scope
    ...some more work on 'i'.
  }
```
So we explicitly limit the lifetime of variables both from above and below. Makes code so much easier to understand.

File: source/simulator/nullspace.cc [hunk 21]
```diff
@@ -81,196 +91,296 @@ namespace aspect
...
     for (cell = dof_handler.begin_active(); cell != dof_handler.end(); ++cell)
       if (cell->is_locally_owned())
         {
           fe.reinit (cell);
-          q_points = fe.get_quadrature_points();
-          fe.get_function_values(relevant_dst, fe_vals);
+          const std::vector<Point<dim> > &q_points = fe.get_quadrature_points();
+
+          //Get the velocity at each quadrature point
+          std::vector< Tensor<1,dim> > velocities( q_points.size() );
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: Move the declaration of this variable out of the loop over all cells so that memory has to be allocated only once, not once per cell.

**Comment by tjhei** [comment]
Ian, can you please run the following tests on your machine and check if their new output makes sense?
	107 - periodic_box_freesurface (Failed)
	119 - remove_angular_momentum (Failed)
	120 - remove_net_rotation (Failed)

If yes, update the output from your machine.

**Comment by tjhei** [comment]
We also need some additional tests, I fear. Are you willing to create a few more variations of the existing ones to exercise the different code paths?

File: doc/manual/manual.tex [hunk 22]
```diff
@@ -1486,6 +1486,85 @@ \subsubsection{Free surface stabilization}
 
 An example of a simple model which uses a free surface may be found in Section \ref{sec:cookbooks-freesurface}.
 
+
+\subsection{Nullspace removal}
+
+The Stokes equation (\ref{eq:stokes-1}) only involves symmetric gradients of the velocity, and as such 
+the velocity is determined only up to rigid-body motions (that is to say, translations and rotations).
```
Comment (bangerth) [inline doc/manual/manual.tex]: ...unless you specify velocity boundary conditions that determine the velocity uniquely.

Comment (bangerth) [inline doc/manual/manual.tex]: ah, fired too quickly of course -- too many distractions in my life :-(

Comment (tjhei) [inline doc/manual/manual.tex]: which he says in the next sentence. :-)

File: doc/manual/manual.tex [hunk 23]
```diff
@@ -1486,6 +1486,85 @@ \subsubsection{Free surface stabilization}
...
+
+Usually the user will be able to determine beforehand whether their problem has a nullspace.  For instance, 
+a model in a spherical shell geometry with free-slip boundary conditions at the top and bottom will 
+have a rigid-body rotation in its nullspace (but not translations, as the boundary conditions do not 
+allow flow through them).  That is to say, the solver may be able to come up with a solution to 
+the Stokes operator, but that solution plus an arbitrary rotation is also an equally valid solution.
+
+Another example is a model in a Cartesian box with periodic boundary conditions in the x-direction, 
+and free slip boundaries on the top and bottom. This setup has arbitrary translations along the x-axis 
+in its nullspace, so any solution plus an arbitrary x-translation is also a solution.
```
Comment (bangerth) [inline doc/manual/manual.tex]: put dollar signs around the `x` here as they denote mathematical symbols.

File: doc/manual/manual.tex [hunk 24]
```diff
@@ -1486,6 +1486,85 @@ \subsubsection{Free surface stabilization}
...
+There are two varieties of nullspace removal implemented: removing net linear/angular momentum, and 
+removing net translations/rotations. 
+
+For removing linear momentum we search for a constant velocity vector $\bf c$ such that 
+
+\begin{equation*}
+\int_\Omega \rho ({\bf u - c}) = 0
+\end{equation*}
+
+This may be solved by realizing that $\int_\Omega \rho {\bf u} = {\bf p}$, the linear momentum, and
```
Comment (tjhei) [inline doc/manual/manual.tex]: this doesn't read like a whole sentence

**Comment by tjhei** [comment]
Modulo tests and changelog entry, this looks very, very good. Thanks, Ian.

File: doc/manual/manual.tex [hunk 25]
```diff
@@ -1486,6 +1486,85 @@ \subsubsection{Free surface stabilization}
...
+difficult to interpret.  
+
+\aspect{} allows the user to specify if their model has a nullspace. If so, any power in the nullspace 
+is calculated and removed from the solution after every timestep.
+There are two varieties of nullspace removal implemented: removing net linear/angular momentum, and 
+removing net translations/rotations. 
+
+For removing linear momentum we search for a constant velocity vector $\bf c$ such that 
+
+\begin{equation*}
```
Comment (bangerth) [inline doc/manual/manual.tex]: here and in the following, you have a number of empty lines. To latex, these are paragraph breaks. In cases such as these, imagine that the formula was not offset from the text, but just part of the flow of the text. If you think about whether there should be an empty line, do you want there to be a paragraph break?

File: doc/manual/manual.tex [hunk 26]
```diff
@@ -1486,6 +1486,85 @@ \subsubsection{Free surface stabilization}
...
+
+A rotation about the rotation vector $\omega$ is then subtracted from the velocity solution.
+
+Removing the net translations/rotations are idential to their momentum counterparts, but for those the 
+density is dropped from the formulae. For most applications the density should not vary so wildly 
+that there will be an appreciable difference between the two varieties, 
+though removing linear/angular momentum is more physically motivated.
+
+Figure \ref{fig:rigid_rotation} shows the result of removing angular momentum from a convection 
+model in a 2D annulus with free-slip velocity boundary conditions.
```
Comment (bangerth) [inline doc/manual/manual.tex]: It would be useful to identify here what the parameter is that the user needs to set.

Other than that, I like this text a lot -- many thanks!

File: doc/manual/manual.tex (hunk 24 above)
Comment (bangerth) [inline doc/manual/manual.tex]: I stumbled over this as well, but it actually does. You probably think that the verb is missing, but the sentence says "This may be solved by realizing that A equals B, the linear momentum, and C equals D, the total mass."

Comment (bangerth) [inline doc/manual/manual.tex]: :-)

File: source/simulator/nullspace.cc [hunk 27]
```diff
@@ -81,196 +91,296 @@ namespace aspect
...
-          for (unsigned int i=0; i< q_points.size(); i++)
+          if ( ! use_constant_density)
             {
-              in.pressure[i] = fe_vals[i][introspection.component_indices.pressure];
-              in.temperature[i] = fe_vals[i][introspection.component_indices.temperature];
-              for (unsigned int c=0; c<parameters.n_compositional_fields; ++c)
-                in.composition[i][c] = fe_vals[i][introspection.component_indices.compositional_fields[c]];
-              in.position[i] = q_points[i];
+              std::vector<std::vector<double> > composition_values (parameters.n_compositional_fields,
+                                                                    std::vector<double> (q_points.size()));
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: same here -- move the declaration out of the loop.

File: source/simulator/nullspace.cc [hunk 28]
```diff
@@ -81,196 +91,296 @@ namespace aspect
...
-              cross_product(r_perp, r_vec);
-              Tensor<1,dim> v_perp = velocity - (velocity*r_vec)*r_vec/(r_vec.norm_square());
-
-              // calculate a signed scalar angular momentum
-              local_scalar_angular_momentum += fe.JxW(k) * velocity*r_perp * out.densities[k];
-              // calculate a scalar moment of inertia
-              local_scalar_moment += fe.JxW(k) * r_vec.norm_square() * out.densities[k];
+              // get the position and density at this quadrature point
+              Point<dim> r_vec = q_points[k];
+              double rho = (use_constant_density ? 1.0 : out.densities[k]);
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: make these two const

**Comment by bangerth** [comment]
Yes, I want to echo @tjhei 's comments -- great work, all around. I hope you forgive my many nitpicks -- many of them are really just stylistic issues and you will quickly absorb them into your programming habits and future patches will become a lot easier.

**Comment by ian-r-rose** [comment]
No problem at all, I am glad that aspect has high standards :-)

I am working through these edits -- be advised that at this point this PR depends on dealii/dealii#864 , so should not be merged until that is.

**Comment by tjhei** [comment]
> be advised that at this point this PR depends on dealii/dealii#864 

I would prefer we make ASPECT work with deal 8.2.1 for some time. So leave your MPI functions in. You can use an ifdef to use the new deal.II functionality if present.

**Comment by ian-r-rose** [comment]
Okay, I think that is most of it.  I am unsure what to add with regards to new tests, especially since the periodic_box tests have been causing difficulty.  Something like the net_rot_broken.prm in #304 could work, though it takes a long time to run.

**Comment by bangerth** [comment]
Outstanding! Can you squash the patches into one (or a number of logically independent ones, if that is an option)?

@tjhei feel free to merge if you're happy with it too.

**Comment by ian-r-rose** [comment]
Before I squash, the tester build is currently failing due to not having access to the new Utilities::MPI::sum functions.  I have preprocessor checks that will go to fallbacks, but they won't work until dealii/dealii#304 is merged.

Should I wait, or edit the preprocessor checks?

**Comment by tjhei** [comment]
It is failing for different reasons:
1.
```
/aspect-tester/aspect/source/simulator/nullspace.cc:151:21: warning: variable length arrays are a C99 feature [-Wvla-extension]
      Number entries[ n_entries ];
```
@bangerth thoughts on this? I would prefer we switch back to a std::vector.

2. 
```
/aspect-tester/aspect/source/simulator/nullspace.cc:157:7: error: no matching function for call to 'sum'
      dealii::Utilities::MPI::sum( entries, mpi_communicator, global_entries );
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/deal.II/installedclang/include/deal.II/base/mpi.h:424:10: note: candidate template ignored: could not match 'const T [N]' against 'double [n_entries]'
```
Related problem because clang is unable to figure out the size at compile time.

File: include/aspect/utilities.h (hunk 17 above)
Comment (tjhei) [inline include/aspect/utilities.h]: Ian, these lines are still left over in your PR but I think you can remove them, right?

File: source/simulator/nullspace.cc [hunk 29]
```diff
@@ -81,196 +90,364 @@ namespace aspect
...
+     * Perform an MPI sum of the entries of a symmetric tensor.
+     */
+    template <int rank, int dim, typename Number>
+    inline
+    SymmetricTensor<rank,dim,Number>
+    sum (const SymmetricTensor<rank,dim,Number> &local,
+         const MPI_Comm &mpi_communicator)
+    {
+      const unsigned int n_entries = local.n_independent_components;
+      Number entries[ n_entries ];
```
Comment (bangerth) [inline source/simulator/nullspace.cc]: I think the warning/error @tjhei refers to in the general comments should go away if you write this as
```
  const unsigned int n_entries = SymmetricTensor<rank,dim>::n_independent_components;
  Number entries[ n_entries ];
```
or as
```
  const unsigned int n_entries = SymmetricTensor<rank,dim>::n_independent_components;
  Number entries[ SymmetricTensor<rank,dim>::n_independent_components ];
```

Comment (ian-r-rose) [inline source/simulator/nullspace.cc]: Hmmm, I get incomplete type errors trying this.  Switching back to dynamic allocation using an std::vector works fine.

**Comment by ian-r-rose** [comment]
Okay, I think that this is about all I can do from my end.  The clang errors look to be gone.  The tests which are failing on the tester pass on my system.  Say the word and I can squash the commits...

**Comment by bangerth** [comment]
Do it, I like it!

**Comment by tjhei** [comment]
Okay, I will fix the tests and merge...
