### PR TITLE
[WIP] Fastscape c++ integration with adapter

### PR DESCRIPTION
**Pull request by Minerallo**
### Description

This PR is a follow-up to [#5323](https://github.com/geodynamics/aspect/pull/5323).  
Since development has moved to a new main branch, this new PR continues the work with a **rebased and updated version** of the FastScape coupling plugin.

The key update in this version is the use of the `FastScapeAdapter` interface by @benbovy and @MFraters , which provides a consistent deal.II mesh-based surface coupling for both **Box** and **SphericalShell** geometries.

The current objective is to restore functionality for the **Box geometry**, now using the adapter interface. **SphericalShell support** will be integrated next.

---

#### Before your first pull request:

- [ ] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.

#### For all pull requests:

- [ ] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

#### For new features/models or changes of existing features:

- [ ] I have tested my new feature locally to ensure it is correct.
- [ ] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
- [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

File: source/mesh_deformation/fastscapecc.cc [hunk 1]
```diff
@@ -239,26 +243,37 @@ namespace aspect
...
-
-              // Map to surface mesh index and assign
-              const unsigned int index = this->vertex_index(pos);
-              surface_solution[index] = projected_velocity;
-                
-//                Test if the velocity are properly projected
-//            if (this->get_timestep_number() == 1 && index < 10) // Only a few samples
-//              this->get_pcout() << "Surface velocity at " << pos
-//                                << " = " << projected_velocity << " m/s" << std::endl;
+              double projected_elevation = 0.0;
```
Comment (Minerallo) [inline source/mesh_deformation/fastscapecc.cc]: Here we store both the surface-normal velocity and elevation (z or radius) for initializing FastScape with any pre-existing topography.

File: include/aspect/mesh_deformation/fastscapecc_adapter.h [hunk 2]
```diff
@@ -0,0 +1,390 @@
...
+#  include <xtensor/containers/xarray.hpp>
+#  include <xtensor/containers/xtensor.hpp>
+#endif
+
+#include <fastscapelib/grid/base.hpp>
+
+// Up until FastScape++ 0.2.2, there was a file xtensor_utils.hpp that declared
+// alias types that are used elsewhere. After that, the file went away, see
+//   https://github.com/fastscape-lem/fastscapelib/pull/155
+// but we still need the contents and so have to declare them ourselves.
```
Comment (benbovy) [inline include/aspect/mesh_deformation/fastscapecc_adapter.h:59]: Fastscapelib's flexible container interface has indeed changed since v0.2.2, but it hasn't been released yet.

Wouldn't be easier to stick with the latest stable release of Fastscapelib, and then update the code here (or in a follow-up PR) to use the new container interface once v0.3.0 is released?

Since the integration between ASPECT is not yet finalized (and will likely be very new at the time when Fastscapelib v0.3.0 will be released - hopefully very shortly), I guess that it is fine to require the last released version as a minimum working version in ASPECT?

Comment (bangerth) [reply include/aspect/mesh_deformation/fastscapecc_adapter.h:59]: @benbovy I tried yesterday to get things to work with the current Fastscapelib and Xtensor versions. I think I got it to work with the current Xtensor, but the adapters do not work with the current Fastscapelib version. I get errors of the sort
```
/home/bangerth/bin/fastscapelib/include/fastscapelib/grid/base.hpp:324:15: error: no type named ‘container_selector’ in ‘using fastscapelib::grid<fastscapelib::dealii_grid<dealii::Triangulation<1, 2>, fastscapelib::xt_selector> >::inner_types = struct fastscapelib::grid_inner_types<fastscapelib::dealii_grid<dealii::Triangulation<1, 2>, fastscapelib::xt_selector> >’ {aka ‘struct fastscapelib::grid_inner_types<fastscapelib::dealii_grid<dealii::Triangulation<1, 2>, fastscapelib::xt_selector> >’}
  324 |         using container_selector = typename inner_types::container_selector;
      |               ^~~~~~~~~~~~~~~~~~
/home/bangerth/bin/fastscapelib/include/fastscapelib/grid/base.hpp:325:15: error: no type named ‘container_selector’ in ‘struct fastscapelib::grid_inner_types<fastscapelib::dealii_grid<dealii::Triangulation<1, 2>, fastscapelib::xt_selector> >’
  325 |         using container_type = fixed_shape_container_t<container_selector,
      |               ^~~~~~~~~~~~~~
/home/bangerth/bin/fastscapelib/include/fastscapelib/grid/base.hpp:329:15: error: no type named ‘container_selector’ in ‘struct fastscapelib::grid_inner_types<fastscapelib::dealii_grid<dealii::Triangulation<1, 2>, fastscapelib::xt_selector> >’
  329 |         using c_inner_types = container_impl<container_type>;
      |               ^~~~~~~~~~~~~
/home/bangerth/bin/fastscapelib/include/fastscapelib/grid/base.hpp:344:15: error: no type named ‘container_selector’ in ‘struct fastscapelib::grid_inner_types<fastscapelib::dealii_grid<dealii::Triangulation<1, 2>, fastscapelib::xt_selector> >’
  344 |         using neighbors_indices_type = xt::xtensor<size_type, 1>;
      |               ^~~~~~~~~~~~~~~~~~~~~~
/home/bangerth/bin/fastscapelib/include/fastscapelib/grid/base.hpp:347:15: error: no type named ‘container_selector’ in ‘struct fastscapelib::grid_inner_types<fastscapelib::dealii_grid<dealii::Triangulation<1, 2>, fastscapelib::xt_selector> >’
  347 |         using nodes_status_type = fixed_shape_container_t<container_selector,
      |               ^~~~~~~~~~~~~~~~~
[...]
```
Given my limited time here, my plan for today is to get things to work with Fastscapelib 0.2.2 and Xtensor 0.25, since that's the setup that all of you seem to be using. That's not ideal -- I think in the long run we should support the current Fastscapelib main branch, if only because that's where all of the development is happening. But at least for today, I'll have to stay with 0.2.2.

If you or @Minerallo wanted to spend a bit of time to change the adapters so that they support current Fastscapelib main branch, that would of course be fantastic.

Comment (benbovy) [reply include/aspect/mesh_deformation/fastscapecc_adapter.h:59]: > my plan for today is to get things to work with Fastscapelib 0.2.2 and Xtensor 0.25, since that's the setup that all of you seem to be using.

It should normally work (at least for the `fastscapelib::dealii_grid` adapter), I could successfully compile #6204 using fastscapelib 0.2.2 and xtensor 0.25, although it was a few months ago. One possible issue is a known bug with clang 19 and xtensor 0.25 (it has been solved in xtensor 0.26, which unfortunately has also some "little annoying" breaking changes).

> I think in the long run we should support the current Fastscapelib main branch, if only because that's where all of the development is happening

Yes I fully agree!

My short-term plan is:

- update Fastscapelib with the xtensor 0.26 changes (starting with what you've done in https://github.com/fastscape-lem/fastscapelib/pull/174) ; unfortunately it will certainly be too much of a burden to maintain compatibility with xtensor 0.25.
- release Fastscapelib 0.3.0
- submit changes here (or in a follow-up PR) to support Fastscapelib 0.3.0 and xtensor 0.26 (as the minimum versions required by ASPECT)

Does that sound like a good plan to you?

Comment (bangerth) [reply include/aspect/mesh_deformation/fastscapecc_adapter.h:59]: Yes, good plan indeed! With the other patches I've posted (or their 0.2.2 equivalent), I've finally managed to compile with Fastscape 0.2.2, Xtensor 0.25 and XTL 0.7.7. All the patches I needed for 0.2.2 I've also posted against the current Fastscape `main` branch. So I'm in a better place right now than I was in the morning. I can now finally compile at least :-)

**Comment by bangerth** [comment]
@Minerallo I've been reading through some parts of the code and found that there are a number of member variables that are either not used, or only ever set. Specifically, these are:

- [ ] `fs_seed`: never used
- [ ] `p`: I could not find where this variable is read from the input file. The variable name is too short to tell whether it's used anywhere :-)
- [ ] `node_tolerance`: I don't think this is used anywhere
- [ ] `precision`: This variable is set, but I don't think it's ever used.

It's possible that you have plans for some of these variables. But if you don't, would you mind pulling the newest version of the branch (including my commits) and remove these variables? Feel free to check off the checkboxes above once you've done that.

**Comment by Minerallo** [comment]
> @Minerallo I've been reading through some parts of the code and found that there are a number of member variables that are either not used, or only ever set. Specifically, these are:
> 
> * [x]  `fs_seed`: never used
> * [x ]  `p`: I could not find where this variable is read from the input file. The variable name is too short to tell whether it's used anywhere :-)
> * [x]  `node_tolerance`: I don't think this is used anywhere
> * [x ]  `precision`: This variable is set, but I don't think it's ever used.
> * [x ]  `restart`: Never used.
> * [x ]  `end_time`: This variable is read from the input file, but then never used. If you plan on using it, my preference would still be to get the end time from the `SimulatorAccess` object, rather than duplicate it in this class.
okay
> 
> It's possible that you have plans for some of these variables. But if you don't, would you mind pulling the newest version of the branch (including my commits) and remove these variables? Feel free to check off the checkboxes above once you've done that.

@bangerth I have removed all the variables for now, and will add them back if we need them later. 
p is the slob exponent for multidirectonal flow, this is computed internally in fastscapelib c++ now, right @benbovy ?

**Comment by bangerth** [comment]
There is an issue with `n_grid_nodes`, as just discussed.

For the box model, this variable isn't set at all. For the spherical model, you do
```
          n_grid_nodes = spherical_vertex_index_map.size();
```
but then (for both cases), in `initialize()`, you do
```
      n_grid_nodes = surface_mesh.n_active_cells();
```
which seems wrong simply based on the words: The left hand side indicates a number of nodes, the right hand side a number of cells.

Perhaps this kind of patch would seem right? I don't know what the rest of the code in this file does yet, so I'll let you figure out whether this makes sense:
```
--- a/source/mesh_deformation/fastscapecc.cc
+++ b/source/mesh_deformation/fastscapecc.cc
@@ -59,8 +59,6 @@ namespace aspect
       this->get_pcout() << "Geometry model type: " << typeid(geom_model).name() << std::endl;
 
       init_surface_mesh(geom_model);
-
-      n_grid_nodes = surface_mesh.n_active_cells();
     }
   
     template <int dim>
@@ -136,11 +134,13 @@ namespace aspect
                   }
               }
 
-          n_grid_nodes = spherical_vertex_index_map.size();
+          AssertDimension (spherical_vertex_index_map.size(), surface_mesh.n_used_vertices());
         }
       else
         AssertThrow(false, ExcMessage("FastScapecc plugin only supports Box or Spherical Shell geometries."));
 
+      n_grid_nodes = surface_mesh.n_used_vertices();
+
 
       // Having create the mesh, now set up the DoFHandlers and constraints objects
       surface_mesh_dof_handler.reinit(surface_mesh);
```
If that does make sense, please apply the patch for you locally.

**Comment by Minerallo** [comment]
yes I would think that  n_used_vertices()  make more sense to use to set the vectors using the patch. 

| Quantity                          | Value |
|----------------------------------|-------|
| `surface_mesh.n_active_cells()`  | 100   |
| `surface_mesh.n_used_vertices()` | 120   |

**Comment by benbovy** [comment]
> which seems wrong simply based on the words: The left hand side indicates a number of nodes, the right hand side a number of cells.

FWIW, a Fastscapelib grid has no concept of a cell. Fastscapelib's algorithms for flow routing and erosion only need a grid (or a graph) of nodes connected to their direct neighbors. What those algorithms also need is an area surrounding each node, which may correspond to the area of a cell around the node (e.g., cell center) although the Fastscapelib doesn't need to know the exact geometry of the cell (which is expensive to store). There's some explanation here too:  https://fastscapelib.readthedocs.io/en/latest/guide_grids.html#grid-representation

Something that we discussed during our last ASPECT/Fastscapelib coupling sprint in Potsdam: a Fastscapelib grid node may correspond to the center (centroid) of an ASPECT (deal.II) mesh cell, a node's neighbors may correspond to all adjacent cells and a node's "area" may correspond to the cell area. I'm not sure to remember how data fields in ASPECT are mapped to cell vertices (i.e., nodes) vs. cells in a deal.II mesh, but this is important to take into account when mapping ASPECT data onto a Fastscapelib grid.

**Comment by bangerth** [comment]
I see. I'll let the two of you figure out what is the appropriate approach. The current state does not seem useful since the variable is first set for the spherical shell grid in `init_surface_mesh()` (but not for the box geometry), and then immediately overwritten at the end of `initialize()`. I don't understand the code well enough to say how to fix this and will gladly let you figure this out :-)

**Comment by benbovy** [comment]
In #6204 the `n_grid_nodes` variable was set only once in `initialize()` after calling `init_surface_mesh()` for the appropriate geometry.

https://github.com/benbovy/aspect/blob/0a1a7f951bd878667d67b7fd0ed9996a91a58bde/source/mesh_deformation/fastscapecc.cc#L51-L101

I'm not sure why it has been changed since then.

I can try helping to figure out how to fix any issue related to `n_grid_nodes` (as it was implemented in #6204). However I might not be familiar enough with ASPECT to figure out what exactly is going on and what is needed, unfortunately.

**Comment by bangerth** [comment]
OK, that suggests that 
```
n_grid_nodes = surface_mesh.n_active_cells();
```
is indeed the right piece of code, and the presence of 
```
n_grid_nodes = spherical_vertex_index_map.size();
```
is wrong? @Minerallo I think I'll leave this to you then!

**Comment by benbovy** [comment]
> p is the slop exponent for multidirectonal flow, this is computed internally in fastscapelib c++ now, right @benbovy ?

@Minerallo in Fastscapelib C++ this is a parameter of the [`multi_flow_router`](https://fastscapelib.readthedocs.io/en/latest/api_cpp/flow.html#_CPPv4N12fastscapelib17multi_flow_routerE) [flow operator](https://fastscapelib.readthedocs.io/en/latest/guide_flow.html#flow-operators). You can find some examples of usage here: https://fastscapelib.readthedocs.io/en/latest/guide_flow.html#flow-routing-strategies.

File: source/mesh_deformation/fastscapecc.cc [hunk 3]
```diff
@@ -0,0 +1,853 @@
...
+            { fastscapelib::single_flow_router() }
+          );
+
+          // 4. Set base level nodes
+          std::vector<std::size_t> base_level_nodes = {0};
+          flow_graph.set_base_levels(base_level_nodes);
+
+          // 5. Build the erosion model
+          auto spl_eroder = fastscapelib::spl_eroder<FlowGraphType>(
+            fastscapelib::make_spl_eroder(flow_graph, kff, n, m, kdd)
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc]: `kdd` is not bedrock diffusivity. [`make_spl_eroder`](https://fastscapelib.readthedocs.io/en/latest/api_cpp/eroder.html#_CPPv4I00EN12fastscapelib15make_spl_eroderE10spl_eroderI2FGER2FGRR1Kddd) creates an eroder class for Stream Power Law [channel erosion](https://fastscapelib.readthedocs.io/en/latest/api_cpp/eroder.html#channel-erosion). The last parameter controls the Newton-Raphson convergence for the non-linear case n != 1 (`slope_exp` parameter).

Actually there's no hillslope diffusion here.

File: source/mesh_deformation/fastscapecc.cc [hunk 4]
```diff
@@ -485,7 +485,7 @@ namespace aspect
           fastscapelib::spl_eroder<FlowGraphType> spl_eroder
           =
             // fastscapelib::make_spl_eroder(flow_graph, kff, n, m, 1e-5)
-            fastscapelib::make_spl_eroder(flow_graph, kff, n, m, 1e-5);
+            fastscapelib::make_spl_eroder(flow_graph, 1e-6, 0.4, 1, 1e-5);
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc]: The values make more sense than the variables, `m` (area exponent) and `n` (slope exponent) were flipped. The right order is:

```cpp
fastscapelib::make_spl_eroder(flow_graph, kff, m, n, 1e-5);
```

(side note: this is also why I prefer the names `area_exp` / `slope_exp` over `m` / `n` to avoid confusion and one character variable names).

File: source/mesh_deformation/fastscapecc.cc [hunk 5]
```diff
@@ -0,0 +1,1064 @@
...
+
+          // 5. Build the erosion model
+          fastscapelib::spl_eroder<FlowGraphType> spl_eroder
+          =
+            // fastscapelib::make_spl_eroder(flow_graph, kff, n, m, 1e-5)
+            fastscapelib::make_spl_eroder(flow_graph, 5e-4, 0.4, 1, 1e-5);
+          std::cout << "KFF : " << kff<< std::endl;
+
+          //Only for raster grid 
+          //To propose if we add back the raster grid option later
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc:635]: Fastscapelib's diffusion is indeed only for the fixed-resolution raster grid since this is a requirement of the ADI numerical scheme used to efficiently solve diffusion.

If I understood correctly, there's an aspect diffusion plugin in the works? Or maybe already working for box geometry? I guess that it will be easier to reuse that plugin on the deal.II grid used by Fastscape instead of introducing a special case here?

File: source/mesh_deformation/fastscapecc.cc [hunk 6]
```diff
@@ -0,0 +1,1061 @@
...
+            
+
+// TODO: This is a pretty arbitrary cell, with a pretty arbitrary cell diameter. Is that what you
+// want? If so, perhaps say so in a comment and explain what it is used for.
+//
+// Separately, let's call this variable surface_cell_area in concordance with our convention
+          const double surface_cell_area = surface_mesh.begin_active()->measure();
+
+          // 1. Create the FastScape grid adapter
+// TODO: I haven't looked at the GridAdapter yet, but we should see whether we can't get rid of the const_cast.
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc:600]: I think it should work without the `const_cast`? The Fastscapelib grid adapter class internally keeps a non-const reference to the underlying mesh (although the adapter class shouldn't change any state of the underlying mesh).

File: source/mesh_deformation/fastscapecc.cc [hunk 7]
```diff
@@ -0,0 +1,1061 @@
...
+            // fastscapelib::make_spl_eroder(flow_graph, kff, n, m, 1e-5)
+            fastscapelib::make_spl_eroder(flow_graph, kff, area_exp, slope_exp, 1e-5);
+          std::cout << "KFF : " << kff<< std::endl;
+
+          //Only for raster grid 
+          //To propose if we add back the raster grid option later 
+          // auto diffusion_eroder = fastscapelib::make_diffusion_adi_eroder(grid, kdd);
+
+         // uplift rate in meters per year for Fastscape
+          std::vector<double> uplift_rate_in_m_year(vz.size());
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc]:
```suggestion
          xt::xarray<double> uplift_rate_in_m_year({ vz.size() });
```

Create directly an xtensor container instead of creating an `std::vector` and later use `xt::adapt` to make it xtensor-compatible. Unless this variable is later used by some function that specifically requires an `std::vector` (note that if those functions require STL-compatible they should probably work with xtensor containers as well, maybe with little adjustement). See, e.g., https://xtensor.readthedocs.io/en/latest/quickref/basic.html.

This could probably be done with other variables as well.

File: source/mesh_deformation/fastscapecc.cc [hunk 8]
```diff
@@ -0,0 +1,1061 @@
...
+            elevation_initialized = true;
+            std::cout << "[DEBUG INIT] Initialized elevation from ASPECT solution.\n";
+          }
+          else
+          {
+            std::cout << "[DEBUG INIT] Reusing elevation from previous timestep.\n";
+          }
+          // auto elevation      = xt::adapt(h, shape);
+          auto elevation_old  = xt::adapt(h_old, shape);
+          auto uplift_rate    = xt::adapt(uplift_rate_in_m_year, shape);
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc]: another variable as `xt::adapt(...)` may not be needed (see https://github.com/geodynamics/aspect/pull/6389/files#r2154251150).

File: source/mesh_deformation/fastscapecc.cc [hunk 9]
```diff
@@ -0,0 +1,1064 @@
...
+
+          //To fix the borders for box models
+          auto row_bounds = xt::view(uplift_rate, xt::keep(0, -1), xt::all());
+          row_bounds = 0.0;
+          auto col_bounds = xt::view(uplift_rate, xt::all(), xt::keep(0, -1));
+          col_bounds = 0.0;
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc]: This is likely wrong. It tries to create views of `uplift_rate` as a 2-dimensional array, but `uplift_rate` is actually a 1-dimensional array with size = `n_grid_nodes` (i.e., the grid adapter's size).

I guess that the goal is to set fixed "boundary" conditions? This can be done in a grid-agnostic way by iterating over the flow graph's [base level nodes](https://fastscapelib.readthedocs.io/en/latest/api_cpp/flow.html#_CPPv4NK12fastscapelib10flow_graph11base_levelsEv), e.g.,

```cpp
for (auto& bi : flow_graph.base_levels())
{
   uplift_rate[bi] = 0.0;
}
```

(I haven't run and checked the code above)

File: source/mesh_deformation/fastscapecc.cc [hunk 10]
```diff
@@ -0,0 +1,1068 @@
...
+            // fastscapelib::make_spl_eroder(flow_graph, kff, n, m, 1e-5)
+            fastscapelib::make_spl_eroder(flow_graph, 5e-4, 0.4, 1, 1e-5);
+          std::cout << "KFF : " << kff<< std::endl;
+
+          //Only for raster grid 
+          //To propose if we add back the raster grid option later 
+          // auto diffusion_eroder = fastscapelib::make_diffusion_adi_eroder(grid, kdd);
+
+              // Create an xarray with correct shape_vec
+          xt::xarray<double> uplift_rate_vec = xt::zeros<double>({vz.size()});
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc:639]: Would be safe to have an assertion check that `vz.size()` equals `grid.size()` (I guess it should be equal).

File: source/mesh_deformation/fastscapecc.cc [hunk 11]
```diff
@@ -0,0 +1,1068 @@
...
+          for (std::size_t i = 0; i < vz.size(); ++i)
+              uplift_rate_vec[i] = vz[i] / year_in_seconds;
+
+          // Reshape uplift_rate to match grid shape (same as elevation)
+          auto uplift_rate = xt::adapt(uplift_rate_vec.data(), shape);
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc:644]: Unless I miss something, this variable `uplift_rate` is not needed. `uplift_rate_vec` should already have the right shape (1-dimensional array with size equal to grid size) and may be reused directly below.

Same for other variables `auto var_name = xt::adapt(...)` (like `elevation` and `elevation_old` below): they are likely not needed either. Instead you can create `xt::xarray` containers directly and assign the data elements to them like if they were `std::vector` containers.

File: source/mesh_deformation/fastscapecc.cc [hunk 12]
```diff
@@ -0,0 +1,1068 @@
...
+//   double topography;
+//   double surface_uplift_rate;
+// };
+// and then you store everything in a
+// std::multimap<types::global_dof_index, ValuesAtSurfaceVertex> surface_vertex_to_surface_values;
+// Note that here I chose a multimap because you visit vertices more than once from all of
+// the adjacent cells, at least in the current code you enter the same vertex into
+//the temp vectors multiple times. I *think* that you should get the same values every
+//time you visit a vertex, so perhaps a std::map is a better choice.
+      std::vector<std::vector<double>> temporary_variables(3, std::vector<double>());
```
Comment (benbovy) [inline source/mesh_deformation/fastscapecc.cc]: I agree using a struct / map would be clearer.

I'm struggling to follow the logic here. I guess that the goal of using temporary variables is for gathering / merging together data from the MPI processes, right? In the case of a single process, the data is simply copied through the temporary variables... Is that correct?

For better clarity if would be nice if this logic could be refactored into a separate function that returns new (xtensor) array containers for topography and surface uplift rate. If it is too expensive to create and re-allocate new array containers each time, the function could instead take topography and surface uplift rate arrays as input, maybe resize them and update their values (same for the temporary structures if needed). IIUC we could even try to optimize the case of a single MPI process (i.e., bypass temporary variables).

File: source/mesh_deformation/fastscapecc.cc (hunk 5 above)
Comment (bangerth) [reply source/mesh_deformation/fastscapecc.cc:635]: ASPECT has a surface diffuser in a different mesh deformation plugin. I'm not entirely sure at the moment whether one can have more than one surface deformation plugin, though.

Comment (bangerth) [reply source/mesh_deformation/fastscapecc.cc:635]: Separately, though: ASPECT's diffuser works on the ASPECT mesh, but that is for most simulations going to be substantially coarser than FastScape++'s mesh. As a consequence, I think at least in the long run it would be useful to have surface diffusion work within FastScape++.

File: source/mesh_deformation/fastscapecc.cc (hunk 12 above)
Comment (bangerth) [reply source/mesh_deformation/fastscapecc.cc]: @benbovy I *think* you're interpreting the reasons behind this code right (but then, of course, I didn't write it and so don't know). When you do plain MPI, working with regular arrays such as those here makes sense. But in ASPECT, we can use deal.II functions such as `Utilities::MPI::isend/ireceive` that can deal with arbitrary data structures and so sending a map is no more work than sending a vector. I think that will make the code easier to read. 

In the long run, I want to separate out the code that evaluates the ASPECT solution at a set of points into a separate function, because we also need that when interfacing with other surface codes. But that's for a later step.

**Comment by bangerth** [comment]
@Minerallo FYI, I implemented the use of deal.II's send/receive functions. This should make it substantially easier to switch to the map.
